"""
lingAI LoRA超参搜索 — 灵极优(lingminopt)
搜索空间: rank × lr，评估指标为41道测试通过率。
用于恒源云训练时确定最优LoRA配置。

用法:
  # 本地模拟（不实际训练，生成搜索方案）
  python tests/lora_hyperparam_search.py --dry-run

  # 恒源云执行（需要训练环境）
  python tests/lora_hyperparam_search.py --data /root/autodl-tmp/lingai_7b_data/phase1_antihallucination.jsonl
"""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

SEARCH_SPACE = {
    "lora_rank": [8, 16, 32, 64],
    "lora_alpha": "2x_rank",
    "learning_rate": [1e-5, 2e-5, 5e-5, 1e-4, 3e-4],
    "batch_size": [4],
    "gradient_accumulation": [8],
    "epochs": [3],
    "warmup_steps": [50],
    "weight_decay": [0.01],
    "max_seq_length": [4096],
    "lora_dropout": [0.05],
    "lora_target_modules": "q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj",
}

FIXED_PARAMS = {
    "base_model": "Qwen/Qwen2.5-Coder-7B-Instruct",
    "load_in_4bit": True,
    "bnb_4bit_quant_type": "nf4",
    "bnb_4bit_compute_dtype": "bfloat16",
    "bnb_4bit_use_double_quant": True,
    "gradient_checkpointing": True,
    "lr_scheduler": "cosine",
    "task_type": "CAUSAL_LM",
}

EVAL_TESTS = [
    "HALLUCINATION_02", "HALLUCINATION_03", "HALLUCINATION_04",
    "CODE_BUG_01", "CODE_BUG_04",
    "REASON_01",
    "SDTH_01", "SDTH_03",
    "ZH_03",
]


def generate_trials():
    trials = []
    for rank in SEARCH_SPACE["lora_rank"]:
        for lr in SEARCH_SPACE["learning_rate"]:
            alpha = rank * 2
            trials.append({
                "lora_rank": rank,
                "lora_alpha": alpha,
                "learning_rate": lr,
                "batch_size": SEARCH_SPACE["batch_size"][0],
                "gradient_accumulation": SEARCH_SPACE["gradient_accumulation"][0],
                "epochs": SEARCH_SPACE["epochs"][0],
                "warmup_steps": SEARCH_SPACE["warmup_steps"][0],
                "weight_decay": SEARCH_SPACE["weight_decay"][0],
                "max_seq_length": SEARCH_SPACE["max_seq_length"][0],
                "lora_dropout": SEARCH_SPACE["lora_dropout"][0],
                "lora_target_modules": SEARCH_SPACE["lora_target_modules"],
                "label": f"r{rank}_lr{lr:.0e}",
                **FIXED_PARAMS,
            })
    return trials


def estimate_cost(trial, num_samples=300):
    steps_per_epoch = max(1, num_samples // (trial["batch_size"] * trial["gradient_accumulation"]))
    total_steps = steps_per_epoch * trial["epochs"]
    base_time_per_step = 2.5 if trial["lora_rank"] <= 16 else 3.0 if trial["lora_rank"] <= 32 else 3.5
    estimated_hours = total_steps * base_time_per_step / 3600
    return {
        "steps_per_epoch": steps_per_epoch,
        "total_steps": total_steps,
        "estimated_hours": round(estimated_hours, 2),
        "estimated_cost_cny": round(estimated_hours * 4.5, 1),
    }


def generate_training_script(trial, data_path, output_dir, phase=1):
    alpha = trial["lora_alpha"]
    rank = trial["lora_rank"]
    lr = trial["learning_rate"]
    bs = trial["batch_size"]
    ga = trial["gradient_accumulation"]
    epochs = trial["epochs"]
    warmup = trial["warmup_steps"]
    wd = trial["weight_decay"]
    seq_len = trial["max_seq_length"]
    dropout = trial["lora_dropout"]
    targets = trial["lora_target_modules"]
    label = trial["label"]

    return f"""#!/bin/bash
# LoRA超参搜索 trial: {label} (Phase {phase})
# Generated by lingminopt lora_hyperparam_search.py
set -e

TRIAL_LABEL="{label}_phase{phase}"
DATA="{data_path}"
OUTPUT="{output_dir}/lingai-7b-${{TRIAL_LABEL}}"
BASE_MODEL="Qwen/Qwen2.5-Coder-7B-Instruct"

echo "=== Trial: ${{TRIAL_LABEL}} ==="
echo "rank={rank}, alpha={alpha}, lr={lr}, epochs={epochs}"

python train_lingai_model.py \\
    --model $BASE_MODEL \\
    --data $DATA \\
    --output $OUTPUT \\
    --epochs {epochs} \\
    --batch-size {bs} \\
    --grad-accum {ga} \\
    --lora-r {rank} \\
    --lora-alpha {alpha} \\
    --lora-dropout {dropout} \\
    --lora-target-modules {targets} \\
    --lr {lr} \\
    --warmup-steps {warmup} \\
    --weight-decay {wd} \\
    --max-seq-length {seq_len} \\
    --lr-scheduler cosine \\
    --load-in-4bit \\
    --gradient-checkpointing

echo "=== Trial ${{TRIAL_LABEL}} complete ==="
echo "Output: $OUTPUT"
"""


def dry_run():
    trials = generate_trials()
    print(f"LoRA超参搜索方案 — {len(trials)} trials")
    print(f"搜索空间: rank={SEARCH_SPACE['lora_rank']} × lr={[f'{x:.0e}' for x in SEARCH_SPACE['learning_rate']]}")
    print()

    total_hours = 0
    total_cost = 0
    print(f"{'Trial':<25s} {'Steps':>6s} {'Hours':>7s} {'Cost(CNY)':>10s}")
    print("-" * 55)
    for t in trials:
        cost = estimate_cost(t)
        total_hours += cost["estimated_hours"]
        total_cost += cost["estimated_cost_cny"]
        print(f"{t['label']:<25s} {cost['total_steps']:>6d} {cost['estimated_hours']:>7.2f} {cost['estimated_cost_cny']:>10.1f}")

    print("-" * 55)
    print(f"{'Total':<25s} {'':>6s} {total_hours:>7.1f} {total_cost:>10.1f}")
    print()
    print(f"评估测试 ({len(EVAL_TESTS)}道，9道失败题):")
    for tid in EVAL_TESTS:
        print(f"  - {tid}")

    plan = {
        "timestamp": datetime.now().isoformat(),
        "search_space": SEARCH_SPACE,
        "fixed_params": FIXED_PARAMS,
        "num_trials": len(trials),
        "total_estimated_hours": round(total_hours, 1),
        "total_estimated_cost_cny": round(total_cost, 1),
        "eval_tests": EVAL_TESTS,
        "trials": [
            {**t, "cost_estimate": estimate_cost(t)}
            for t in trials
        ],
    }

    out_path = Path("/home/ai/lingminopt/data/lora_hyperparam_search_plan.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(plan, f, ensure_ascii=False, indent=2, default=str)
    print(f"\n搜索方案已保存: {out_path}")

    rec_path = Path("/home/ai/lingminopt/data/lora_recommended_trials.json")
    recommended = [t for t in trials if t["lora_rank"] == 32]
    with open(rec_path, "w", encoding="utf-8") as f:
        json.dump({"recommended": recommended, "reason": "rank=32是7B模型的标准选择，lr搜索覆盖5个量级"}, f, ensure_ascii=False, indent=2, default=str)
    print(f"推荐trials已保存: {rec_path} (rank=32, {len(recommended)} trials)")


def main():
    parser = argparse.ArgumentParser(description="lingAI LoRA超参搜索")
    parser.add_argument("--dry-run", action="store_true", help="生成搜索方案不执行训练")
    parser.add_argument("--data", type=str, help="训练数据路径")
    parser.add_argument("--output-dir", type=str, default="/root/autodl-tmp/lora_search")
    parser.add_argument("--phase", type=int, default=1, help="训练Phase (1-4)")
    parser.add_argument("--trial-index", type=int, help="执行特定trial")
    args = parser.parse_args()

    if args.dry_run:
        dry_run()
        return

    if not args.data:
        print("错误: 需要指定 --data 训练数据路径")
        sys.exit(1)

    trials = generate_trials()

    if args.trial_index is not None:
        if args.trial_index >= len(trials):
            print(f"错误: trial-index {args.trial_index} 超出范围 (0-{len(trials)-1})")
            sys.exit(1)
        trial = trials[args.trial_index]
        script = generate_training_script(trial, args.data, args.output_dir, args.phase)
        script_path = Path(args.output_dir) / f"train_{trial['label']}_phase{args.phase}.sh"
        script_path.parent.mkdir(parents=True, exist_ok=True)
        script_path.write_text(script)
        print(f"训练脚本已生成: {script_path}")
    else:
        print(f"共{len(trials)}个trials。使用 --trial-index 指定要执行的trial。")
        print("先用 --dry-run 查看所有trials。")


if __name__ == "__main__":
    main()
